// Journal Prompts organized by category and subcategory
// Categories: stoic, cbt, gratitude, reflection

export const prompts = [
  // STOIC REFLECTION - Dichotomy of Control (10)
  {
    id: 'st-dc-001',
    category: 'stoic',
    subcategory: 'dichotomy',
    text: 'What aspects of your current challenge are within your control, and what aspects are outside of it?',
    source: 'Epictetus',
  },
  {
    id: 'st-dc-002',
    category: 'stoic',
    subcategory: 'dichotomy',
    text: 'If you accepted that you cannot control this outcome, what would change about how you approach it?',
    source: 'Epictetus',
  },
  {
    id: 'st-dc-003',
    category: 'stoic',
    subcategory: 'dichotomy',
    text: 'What action within your power would you be proud of, regardless of the outcome?',
    source: 'Marcus Aurelius',
  },
  {
    id: 'st-dc-004',
    category: 'stoic',
    subcategory: 'dichotomy',
    text: 'Are you spending energy worrying about something you cannot influence? What could you focus on instead?',
    source: 'Epictetus',
  },
  {
    id: 'st-dc-005',
    category: 'stoic',
    subcategory: 'dichotomy',
    text: 'What would a wise person focus their attention on in your current situation?',
    source: 'Seneca',
  },
  {
    id: 'st-dc-006',
    category: 'stoic',
    subcategory: 'dichotomy',
    text: 'How much of your stress comes from trying to control things beyond your influence?',
    source: 'Epictetus',
  },
  {
    id: 'st-dc-007',
    category: 'stoic',
    subcategory: 'dichotomy',
    text: 'What is the best possible response you can make to your current circumstances?',
    source: 'Marcus Aurelius',
  },
  {
    id: 'st-dc-008',
    category: 'stoic',
    subcategory: 'dichotomy',
    text: 'If you cannot change the situation, how might you change your relationship to it?',
    source: 'Epictetus',
  },
  {
    id: 'st-dc-009',
    category: 'stoic',
    subcategory: 'dichotomy',
    text: 'What part of this problem depends entirely on your choices and actions?',
    source: 'Epictetus',
  },
  {
    id: 'st-dc-010',
    category: 'stoic',
    subcategory: 'dichotomy',
    text: 'Are you treating an external event as if it were within your control? What would happen if you let go?',
    source: 'Epictetus',
  },

  // STOIC REFLECTION - Virtue Practice (10)
  {
    id: 'st-vp-001',
    category: 'stoic',
    subcategory: 'virtue',
    text: 'Which of the four virtues (wisdom, courage, justice, temperance) do you most need to practice today?',
    source: 'Marcus Aurelius',
  },
  {
    id: 'st-vp-002',
    category: 'stoic',
    subcategory: 'virtue',
    text: 'How can you show more courage in a situation you\'ve been avoiding?',
    source: 'Seneca',
  },
  {
    id: 'st-vp-003',
    category: 'stoic',
    subcategory: 'virtue',
    text: 'Where in your life could you exercise more self-control or moderation?',
    source: 'Marcus Aurelius',
  },
  {
    id: 'st-vp-004',
    category: 'stoic',
    subcategory: 'virtue',
    text: 'What decision are you facing that requires wisdom? What would a wise mentor advise?',
    source: 'Seneca',
  },
  {
    id: 'st-vp-005',
    category: 'stoic',
    subcategory: 'virtue',
    text: 'How have you treated others fairly today? Where could you improve?',
    source: 'Marcus Aurelius',
  },
  {
    id: 'st-vp-006',
    category: 'stoic',
    subcategory: 'virtue',
    text: 'What difficult conversation have you been avoiding? What virtue would help you have it?',
    source: 'Epictetus',
  },
  {
    id: 'st-vp-007',
    category: 'stoic',
    subcategory: 'virtue',
    text: 'If you were being your best self today, what would you do differently?',
    source: 'Marcus Aurelius',
  },
  {
    id: 'st-vp-008',
    category: 'stoic',
    subcategory: 'virtue',
    text: 'What habit or impulse do you need to restrain for your own good?',
    source: 'Seneca',
  },
  {
    id: 'st-vp-009',
    category: 'stoic',
    subcategory: 'virtue',
    text: 'How can you contribute to the common good today?',
    source: 'Marcus Aurelius',
  },
  {
    id: 'st-vp-010',
    category: 'stoic',
    subcategory: 'virtue',
    text: 'What is the right thing to do in a situation where no one is watching?',
    source: 'Epictetus',
  },

  // STOIC REFLECTION - View from Above (10)
  {
    id: 'st-va-001',
    category: 'stoic',
    subcategory: 'view_from_above',
    text: 'Will this matter in five years? In ten? What does that perspective reveal?',
    source: 'Marcus Aurelius',
  },
  {
    id: 'st-va-002',
    category: 'stoic',
    subcategory: 'view_from_above',
    text: 'Imagine viewing your life from the perspective of the entire universe. What seems important now?',
    source: 'Marcus Aurelius',
  },
  {
    id: 'st-va-003',
    category: 'stoic',
    subcategory: 'view_from_above',
    text: 'How would you advise a friend in your exact situation? Can you give yourself the same advice?',
    source: 'Seneca',
  },
  {
    id: 'st-va-004',
    category: 'stoic',
    subcategory: 'view_from_above',
    text: 'If you could see your life from the perspective of your 80-year-old self, what would matter most?',
    source: 'Seneca',
  },
  {
    id: 'st-va-005',
    category: 'stoic',
    subcategory: 'view_from_above',
    text: 'How many people throughout history have faced similar challenges? What can you learn from their example?',
    source: 'Marcus Aurelius',
  },
  {
    id: 'st-va-006',
    category: 'stoic',
    subcategory: 'view_from_above',
    text: 'In the grand scope of your life, how significant is this current problem?',
    source: 'Seneca',
  },
  {
    id: 'st-va-007',
    category: 'stoic',
    subcategory: 'view_from_above',
    text: 'What would your role model think about how you\'re handling this situation?',
    source: 'Epictetus',
  },
  {
    id: 'st-va-008',
    category: 'stoic',
    subcategory: 'view_from_above',
    text: 'If you could observe yourself from outside, what patterns would you notice?',
    source: 'Marcus Aurelius',
  },
  {
    id: 'st-va-009',
    category: 'stoic',
    subcategory: 'view_from_above',
    text: 'How might future generations view the challenges you face today?',
    source: 'Seneca',
  },
  {
    id: 'st-va-010',
    category: 'stoic',
    subcategory: 'view_from_above',
    text: 'Looking back on your life, what moments seemed catastrophic but turned out to be opportunities?',
    source: 'Seneca',
  },

  // STOIC REFLECTION - Premeditatio Malorum (10)
  {
    id: 'st-pm-001',
    category: 'stoic',
    subcategory: 'premeditatio',
    text: 'What challenges might you face today? How will you respond to each with wisdom and virtue?',
    source: 'Seneca',
  },
  {
    id: 'st-pm-002',
    category: 'stoic',
    subcategory: 'premeditatio',
    text: 'If the worst case scenario happened, how would you cope? What strengths would you draw upon?',
    source: 'Seneca',
  },
  {
    id: 'st-pm-003',
    category: 'stoic',
    subcategory: 'premeditatio',
    text: 'What difficult people might you encounter today? How will you maintain your equanimity?',
    source: 'Marcus Aurelius',
  },
  {
    id: 'st-pm-004',
    category: 'stoic',
    subcategory: 'premeditatio',
    text: 'What could go wrong with your plans today? How can you prepare for each possibility?',
    source: 'Seneca',
  },
  {
    id: 'st-pm-005',
    category: 'stoic',
    subcategory: 'premeditatio',
    text: 'Imagine losing something you value. How does this help you appreciate it more fully?',
    source: 'Epictetus',
  },
  {
    id: 'st-pm-006',
    category: 'stoic',
    subcategory: 'premeditatio',
    text: 'What would you do if your current plans completely fell apart? What opportunities might arise?',
    source: 'Seneca',
  },
  {
    id: 'st-pm-007',
    category: 'stoic',
    subcategory: 'premeditatio',
    text: 'How would you handle unexpected bad news today? What would be your first virtuous response?',
    source: 'Marcus Aurelius',
  },
  {
    id: 'st-pm-008',
    category: 'stoic',
    subcategory: 'premeditatio',
    text: 'What fear is holding you back? What would happen if that fear came true, and how would you handle it?',
    source: 'Seneca',
  },
  {
    id: 'st-pm-009',
    category: 'stoic',
    subcategory: 'premeditatio',
    text: 'If you knew you only had one year to live, how would you spend today?',
    source: 'Seneca',
  },
  {
    id: 'st-pm-010',
    category: 'stoic',
    subcategory: 'premeditatio',
    text: 'What setback could be reframed as a chance to practice resilience?',
    source: 'Marcus Aurelius',
  },

  // CBT - Cognitive Distortion Identification (10)
  {
    id: 'cbt-cd-001',
    category: 'cbt',
    subcategory: 'cognitive_distortion',
    text: 'Are you engaging in all-or-nothing thinking? What shades of gray might exist in this situation?',
    source: 'CBT',
  },
  {
    id: 'cbt-cd-002',
    category: 'cbt',
    subcategory: 'cognitive_distortion',
    text: 'Are you mind-reading or assuming you know what others think? What evidence do you actually have?',
    source: 'CBT',
  },
  {
    id: 'cbt-cd-003',
    category: 'cbt',
    subcategory: 'cognitive_distortion',
    text: 'Are you catastrophizing? What is a more realistic assessment of what might happen?',
    source: 'CBT',
  },
  {
    id: 'cbt-cd-004',
    category: 'cbt',
    subcategory: 'cognitive_distortion',
    text: 'Are you filtering out the positive and focusing only on the negative? What good things have you overlooked?',
    source: 'CBT',
  },
  {
    id: 'cbt-cd-005',
    category: 'cbt',
    subcategory: 'cognitive_distortion',
    text: 'Are you personalizing—taking blame for things outside your control? What other factors contributed?',
    source: 'CBT',
  },
  {
    id: 'cbt-cd-006',
    category: 'cbt',
    subcategory: 'cognitive_distortion',
    text: 'Are you using "should" statements? What if you replaced "should" with "could" or "want to"?',
    source: 'CBT',
  },
  {
    id: 'cbt-cd-007',
    category: 'cbt',
    subcategory: 'cognitive_distortion',
    text: 'Are you overgeneralizing from one event? How is this situation unique?',
    source: 'CBT',
  },
  {
    id: 'cbt-cd-008',
    category: 'cbt',
    subcategory: 'cognitive_distortion',
    text: 'Are you labeling yourself based on one behavior? How can you separate the action from your identity?',
    source: 'CBT',
  },
  {
    id: 'cbt-cd-009',
    category: 'cbt',
    subcategory: 'cognitive_distortion',
    text: 'Are you fortune-telling, predicting the future negatively? What other outcomes are possible?',
    source: 'CBT',
  },
  {
    id: 'cbt-cd-010',
    category: 'cbt',
    subcategory: 'cognitive_distortion',
    text: 'Are you letting feelings dictate facts? Just because you feel it, does that make it true?',
    source: 'CBT',
  },

  // CBT - Evidence Gathering (10)
  {
    id: 'cbt-eg-001',
    category: 'cbt',
    subcategory: 'evidence',
    text: 'What evidence supports your current thought? What evidence contradicts it?',
    source: 'CBT',
  },
  {
    id: 'cbt-eg-002',
    category: 'cbt',
    subcategory: 'evidence',
    text: 'If a friend had this thought, what would you tell them? What evidence would you point to?',
    source: 'CBT',
  },
  {
    id: 'cbt-eg-003',
    category: 'cbt',
    subcategory: 'evidence',
    text: 'Have you felt this way before? What actually happened compared to what you predicted?',
    source: 'CBT',
  },
  {
    id: 'cbt-eg-004',
    category: 'cbt',
    subcategory: 'evidence',
    text: 'What would an objective observer notice about this situation?',
    source: 'CBT',
  },
  {
    id: 'cbt-eg-005',
    category: 'cbt',
    subcategory: 'evidence',
    text: 'Are you confusing a thought with a fact? How could you test this thought?',
    source: 'CBT',
  },
  {
    id: 'cbt-eg-006',
    category: 'cbt',
    subcategory: 'evidence',
    text: 'What past experiences might be coloring your interpretation of this situation?',
    source: 'CBT',
  },
  {
    id: 'cbt-eg-007',
    category: 'cbt',
    subcategory: 'evidence',
    text: 'If this thought is true, what is the worst that could happen? How likely is that?',
    source: 'CBT',
  },
  {
    id: 'cbt-eg-008',
    category: 'cbt',
    subcategory: 'evidence',
    text: 'What are three alternative explanations for what happened?',
    source: 'CBT',
  },
  {
    id: 'cbt-eg-009',
    category: 'cbt',
    subcategory: 'evidence',
    text: 'How might you see this situation differently in a week? A month? A year?',
    source: 'CBT',
  },
  {
    id: 'cbt-eg-010',
    category: 'cbt',
    subcategory: 'evidence',
    text: 'What information are you missing? What would you need to know to be more certain?',
    source: 'CBT',
  },

  // CBT - Thought Challenging (10)
  {
    id: 'cbt-tc-001',
    category: 'cbt',
    subcategory: 'thought_challenging',
    text: 'What is a more balanced way to think about this situation?',
    source: 'CBT',
  },
  {
    id: 'cbt-tc-002',
    category: 'cbt',
    subcategory: 'thought_challenging',
    text: 'What would you tell your best friend if they were having this thought?',
    source: 'CBT',
  },
  {
    id: 'cbt-tc-003',
    category: 'cbt',
    subcategory: 'thought_challenging',
    text: 'How can you reframe this setback as an opportunity for growth?',
    source: 'CBT',
  },
  {
    id: 'cbt-tc-004',
    category: 'cbt',
    subcategory: 'thought_challenging',
    text: 'What is a kinder way to talk to yourself about this?',
    source: 'CBT',
  },
  {
    id: 'cbt-tc-005',
    category: 'cbt',
    subcategory: 'thought_challenging',
    text: 'If you stopped believing this thought, how would your behavior change?',
    source: 'CBT',
  },
  {
    id: 'cbt-tc-006',
    category: 'cbt',
    subcategory: 'thought_challenging',
    text: 'What strengths or resources do you have that you might be forgetting?',
    source: 'CBT',
  },
  {
    id: 'cbt-tc-007',
    category: 'cbt',
    subcategory: 'thought_challenging',
    text: 'How might this challenge help you become stronger or wiser?',
    source: 'CBT',
  },
  {
    id: 'cbt-tc-008',
    category: 'cbt',
    subcategory: 'thought_challenging',
    text: 'What is one small action you could take that contradicts this negative thought?',
    source: 'CBT',
  },
  {
    id: 'cbt-tc-009',
    category: 'cbt',
    subcategory: 'thought_challenging',
    text: 'What have you learned from similar situations in the past that could help now?',
    source: 'CBT',
  },
  {
    id: 'cbt-tc-010',
    category: 'cbt',
    subcategory: 'thought_challenging',
    text: 'How would the person you want to become think about this situation?',
    source: 'CBT',
  },

  // GRATITUDE - Specific Gratitude (8)
  {
    id: 'gr-sg-001',
    category: 'gratitude',
    subcategory: 'specific',
    text: 'What small moment today brought you unexpected joy or comfort?',
    source: null,
  },
  {
    id: 'gr-sg-002',
    category: 'gratitude',
    subcategory: 'specific',
    text: 'Who did something kind for you recently, even something small? How did it affect you?',
    source: null,
  },
  {
    id: 'gr-sg-003',
    category: 'gratitude',
    subcategory: 'specific',
    text: 'What is something about your body that you\'re grateful for today?',
    source: null,
  },
  {
    id: 'gr-sg-004',
    category: 'gratitude',
    subcategory: 'specific',
    text: 'What modern convenience made your day easier? What would life be like without it?',
    source: null,
  },
  {
    id: 'gr-sg-005',
    category: 'gratitude',
    subcategory: 'specific',
    text: 'What skill or ability do you have that you sometimes take for granted?',
    source: null,
  },
  {
    id: 'gr-sg-006',
    category: 'gratitude',
    subcategory: 'specific',
    text: 'What challenge have you overcome that you\'re now grateful for having faced?',
    source: null,
  },
  {
    id: 'gr-sg-007',
    category: 'gratitude',
    subcategory: 'specific',
    text: 'What is something beautiful you noticed today, however small?',
    source: null,
  },
  {
    id: 'gr-sg-008',
    category: 'gratitude',
    subcategory: 'specific',
    text: 'What is a memory from your past that still brings you warmth?',
    source: null,
  },

  // GRATITUDE - Negative Visualization (4)
  {
    id: 'gr-nv-001',
    category: 'gratitude',
    subcategory: 'negative_visualization',
    text: 'Imagine you lost your home tomorrow. What aspects of your current living situation are you grateful for?',
    source: 'Seneca',
  },
  {
    id: 'gr-nv-002',
    category: 'gratitude',
    subcategory: 'negative_visualization',
    text: 'If you could never see a loved one again, what would you want them to know? Can you tell them now?',
    source: 'Seneca',
  },
  {
    id: 'gr-nv-003',
    category: 'gratitude',
    subcategory: 'negative_visualization',
    text: 'What if you lost your job or main source of income? What aspects of your work are you grateful for?',
    source: 'Seneca',
  },
  {
    id: 'gr-nv-004',
    category: 'gratitude',
    subcategory: 'negative_visualization',
    text: 'Consider that this could be your last day. What ordinary experiences would you treasure?',
    source: 'Marcus Aurelius',
  },

  // GRATITUDE - Relationship Gratitude (3)
  {
    id: 'gr-rg-001',
    category: 'gratitude',
    subcategory: 'relationship',
    text: 'What quality in a loved one are you most grateful for? Have you told them lately?',
    source: null,
  },
  {
    id: 'gr-rg-002',
    category: 'gratitude',
    subcategory: 'relationship',
    text: 'Who in your life has helped shape who you are today? What specifically did they contribute?',
    source: null,
  },
  {
    id: 'gr-rg-003',
    category: 'gratitude',
    subcategory: 'relationship',
    text: 'What relationship in your life could use more appreciation? How can you show it?',
    source: null,
  },

  // SELF-DISCOVERY - Values Clarification (5)
  {
    id: 'sd-vc-001',
    category: 'reflection',
    subcategory: 'values',
    text: 'What matters most to you in life? Are your daily actions aligned with these values?',
    source: null,
  },
  {
    id: 'sd-vc-002',
    category: 'reflection',
    subcategory: 'values',
    text: 'When do you feel most authentic and true to yourself? What values are you honoring in those moments?',
    source: null,
  },
  {
    id: 'sd-vc-003',
    category: 'reflection',
    subcategory: 'values',
    text: 'If you could only pass on three values to future generations, what would they be and why?',
    source: null,
  },
  {
    id: 'sd-vc-004',
    category: 'reflection',
    subcategory: 'values',
    text: 'What would you do with your life if money were no object? What does this reveal about your values?',
    source: null,
  },
  {
    id: 'sd-vc-005',
    category: 'reflection',
    subcategory: 'values',
    text: 'Where in your life are you compromising your values? What would it take to change this?',
    source: null,
  },

  // SELF-DISCOVERY - Life Review (4)
  {
    id: 'sd-lr-001',
    category: 'reflection',
    subcategory: 'life_review',
    text: 'What chapter of your life are you currently in? How would you title it?',
    source: null,
  },
  {
    id: 'sd-lr-002',
    category: 'reflection',
    subcategory: 'life_review',
    text: 'What is a defining moment from your past that shaped who you are today?',
    source: null,
  },
  {
    id: 'sd-lr-003',
    category: 'reflection',
    subcategory: 'life_review',
    text: 'What would your 10-year-old self think of your life now? What would surprise them?',
    source: null,
  },
  {
    id: 'sd-lr-004',
    category: 'reflection',
    subcategory: 'life_review',
    text: 'What experiences have you had that you once thought were setbacks but now see as gifts?',
    source: null,
  },

  // SELF-DISCOVERY - Goal Reflection (3)
  {
    id: 'sd-gr-001',
    category: 'reflection',
    subcategory: 'goals',
    text: 'What is one thing you\'ve been putting off that would significantly improve your life?',
    source: null,
  },
  {
    id: 'sd-gr-002',
    category: 'reflection',
    subcategory: 'goals',
    text: 'If you could accomplish only one thing this year, what would have the biggest positive impact?',
    source: null,
  },
  {
    id: 'sd-gr-003',
    category: 'reflection',
    subcategory: 'goals',
    text: 'What goal have you given up on that still matters to you? What small step could you take today?',
    source: null,
  },

  // SELF-DISCOVERY - Identity Exploration (3)
  {
    id: 'sd-ie-001',
    category: 'reflection',
    subcategory: 'identity',
    text: 'How would you describe yourself in three words? Are these the words you want to define you?',
    source: null,
  },
  {
    id: 'sd-ie-002',
    category: 'reflection',
    subcategory: 'identity',
    text: 'What roles do you play in life (parent, friend, professional)? Which feel most authentic?',
    source: null,
  },
  {
    id: 'sd-ie-003',
    category: 'reflection',
    subcategory: 'identity',
    text: 'What parts of yourself have you been hiding or suppressing? What would happen if you expressed them?',
    source: null,
  },
];
