// Stoic Quotes from primary sources
// Categories: dichotomy_of_control, adversity, virtue, mortality, relationships, emotions, present_moment, self_improvement

export const quotes = [
  // MARCUS AURELIUS - Meditations (60 quotes)
  {
    id: 'ma-001',
    text: 'You have power over your mind — not outside events. Realize this, and you will find strength.',
    author: 'Marcus Aurelius',
    sourceWork: 'Meditations',
    bookChapter: 'Book 6',
    tags: ['control', 'mindset', 'strength'],
    category: 'dichotomy_of_control',
  },
  {
    id: 'ma-002',
    text: 'Waste no more time arguing about what a good man should be. Be one.',
    author: 'Marcus Aurelius',
    sourceWork: 'Meditations',
    bookChapter: 'Book 10',
    tags: ['action', 'virtue', 'character'],
    category: 'virtue',
  },
  {
    id: 'ma-003',
    text: 'The happiness of your life depends upon the quality of your thoughts.',
    author: 'Marcus Aurelius',
    sourceWork: 'Meditations',
    bookChapter: 'Book 4',
    tags: ['happiness', 'thoughts', 'mindset'],
    category: 'self_improvement',
  },
  {
    id: 'ma-004',
    text: 'Very little is needed to make a happy life; it is all within yourself, in your way of thinking.',
    author: 'Marcus Aurelius',
    sourceWork: 'Meditations',
    bookChapter: 'Book 7',
    tags: ['happiness', 'simplicity', 'mindset'],
    category: 'self_improvement',
  },
  {
    id: 'ma-005',
    text: 'When you arise in the morning, think of what a precious privilege it is to be alive — to breathe, to think, to enjoy, to love.',
    author: 'Marcus Aurelius',
    sourceWork: 'Meditations',
    bookChapter: 'Book 5',
    tags: ['gratitude', 'morning', 'life'],
    category: 'present_moment',
  },
  {
    id: 'ma-006',
    text: 'Dwell on the beauty of life. Watch the stars, and see yourself running with them.',
    author: 'Marcus Aurelius',
    sourceWork: 'Meditations',
    bookChapter: 'Book 7',
    tags: ['beauty', 'perspective', 'wonder'],
    category: 'present_moment',
  },
  {
    id: 'ma-007',
    text: 'The best revenge is not to be like your enemy.',
    author: 'Marcus Aurelius',
    sourceWork: 'Meditations',
    bookChapter: 'Book 6',
    tags: ['revenge', 'character', 'virtue'],
    category: 'virtue',
  },
  {
    id: 'ma-008',
    text: 'Accept the things to which fate binds you, and love the people with whom fate brings you together, and do so with all your heart.',
    author: 'Marcus Aurelius',
    sourceWork: 'Meditations',
    bookChapter: 'Book 6',
    tags: ['acceptance', 'love', 'fate'],
    category: 'relationships',
  },
  {
    id: 'ma-009',
    text: 'It is not death that a man should fear, but he should fear never beginning to live.',
    author: 'Marcus Aurelius',
    sourceWork: 'Meditations',
    bookChapter: 'Book 12',
    tags: ['death', 'life', 'fear'],
    category: 'mortality',
  },
  {
    id: 'ma-010',
    text: 'Never let the future disturb you. You will meet it, if you have to, with the same weapons of reason which today arm you against the present.',
    author: 'Marcus Aurelius',
    sourceWork: 'Meditations',
    bookChapter: 'Book 7',
    tags: ['future', 'anxiety', 'reason'],
    category: 'dichotomy_of_control',
  },
  {
    id: 'ma-011',
    text: 'The object of life is not to be on the side of the majority, but to escape finding oneself in the ranks of the insane.',
    author: 'Marcus Aurelius',
    sourceWork: 'Meditations',
    bookChapter: 'Book 4',
    tags: ['individuality', 'wisdom', 'society'],
    category: 'self_improvement',
  },
  {
    id: 'ma-012',
    text: 'If it is not right do not do it; if it is not true do not say it.',
    author: 'Marcus Aurelius',
    sourceWork: 'Meditations',
    bookChapter: 'Book 12',
    tags: ['truth', 'integrity', 'action'],
    category: 'virtue',
  },
  {
    id: 'ma-013',
    text: 'How much more grievous are the consequences of anger than the causes of it.',
    author: 'Marcus Aurelius',
    sourceWork: 'Meditations',
    bookChapter: 'Book 11',
    tags: ['anger', 'consequences', 'emotions'],
    category: 'emotions',
  },
  {
    id: 'ma-014',
    text: 'The soul becomes dyed with the color of its thoughts.',
    author: 'Marcus Aurelius',
    sourceWork: 'Meditations',
    bookChapter: 'Book 5',
    tags: ['thoughts', 'soul', 'character'],
    category: 'self_improvement',
  },
  {
    id: 'ma-015',
    text: 'Begin each day by telling yourself: Today I shall be meeting with interference, ingratitude, insolence, disloyalty, ill-will, and selfishness.',
    author: 'Marcus Aurelius',
    sourceWork: 'Meditations',
    bookChapter: 'Book 2',
    tags: ['preparation', 'morning', 'expectations'],
    category: 'adversity',
  },
  {
    id: 'ma-016',
    text: 'Loss is nothing else but change, and change is Nature\'s delight.',
    author: 'Marcus Aurelius',
    sourceWork: 'Meditations',
    bookChapter: 'Book 4',
    tags: ['change', 'loss', 'nature'],
    category: 'adversity',
  },
  {
    id: 'ma-017',
    text: 'Look back over the past, with its changing empires that rose and fell, and you can foresee the future too.',
    author: 'Marcus Aurelius',
    sourceWork: 'Meditations',
    bookChapter: 'Book 7',
    tags: ['history', 'perspective', 'future'],
    category: 'present_moment',
  },
  {
    id: 'ma-018',
    text: 'Confine yourself to the present.',
    author: 'Marcus Aurelius',
    sourceWork: 'Meditations',
    bookChapter: 'Book 8',
    tags: ['present', 'focus', 'mindfulness'],
    category: 'present_moment',
  },
  {
    id: 'ma-019',
    text: 'Do not act as if you had ten thousand years to throw away. Death stands at your elbow. Be good for something while you live and it is in your power.',
    author: 'Marcus Aurelius',
    sourceWork: 'Meditations',
    bookChapter: 'Book 4',
    tags: ['death', 'urgency', 'action'],
    category: 'mortality',
  },
  {
    id: 'ma-020',
    text: 'A man\'s worth is no greater than the worth of his ambitions.',
    author: 'Marcus Aurelius',
    sourceWork: 'Meditations',
    bookChapter: 'Book 7',
    tags: ['ambition', 'worth', 'character'],
    category: 'self_improvement',
  },
  {
    id: 'ma-021',
    text: 'No man is happy who does not think himself so.',
    author: 'Marcus Aurelius',
    sourceWork: 'Meditations',
    bookChapter: 'Book 10',
    tags: ['happiness', 'mindset', 'perception'],
    category: 'self_improvement',
  },
  {
    id: 'ma-022',
    text: 'The first rule is to keep an untroubled spirit. The second is to look things in the face and know them for what they are.',
    author: 'Marcus Aurelius',
    sourceWork: 'Meditations',
    bookChapter: 'Book 4',
    tags: ['tranquility', 'truth', 'clarity'],
    category: 'self_improvement',
  },
  {
    id: 'ma-023',
    text: 'What we do now echoes in eternity.',
    author: 'Marcus Aurelius',
    sourceWork: 'Meditations',
    bookChapter: 'Book 5',
    tags: ['action', 'legacy', 'impact'],
    category: 'virtue',
  },
  {
    id: 'ma-024',
    text: 'The impediment to action advances action. What stands in the way becomes the way.',
    author: 'Marcus Aurelius',
    sourceWork: 'Meditations',
    bookChapter: 'Book 5',
    tags: ['obstacles', 'opportunity', 'adversity'],
    category: 'adversity',
  },
  {
    id: 'ma-025',
    text: 'Everything we hear is an opinion, not a fact. Everything we see is a perspective, not the truth.',
    author: 'Marcus Aurelius',
    sourceWork: 'Meditations',
    bookChapter: 'Book 4',
    tags: ['perspective', 'truth', 'judgment'],
    category: 'dichotomy_of_control',
  },
  {
    id: 'ma-026',
    text: 'Receive without pride, let go without attachment.',
    author: 'Marcus Aurelius',
    sourceWork: 'Meditations',
    bookChapter: 'Book 8',
    tags: ['pride', 'attachment', 'equanimity'],
    category: 'emotions',
  },
  {
    id: 'ma-027',
    text: 'Think of yourself as dead. You have lived your life. Now take what\'s left and live it properly.',
    author: 'Marcus Aurelius',
    sourceWork: 'Meditations',
    bookChapter: 'Book 7',
    tags: ['death', 'renewal', 'purpose'],
    category: 'mortality',
  },
  {
    id: 'ma-028',
    text: 'Be tolerant with others and strict with yourself.',
    author: 'Marcus Aurelius',
    sourceWork: 'Meditations',
    bookChapter: 'Book 5',
    tags: ['tolerance', 'discipline', 'relationships'],
    category: 'relationships',
  },
  {
    id: 'ma-029',
    text: 'The best answer to anger is silence.',
    author: 'Marcus Aurelius',
    sourceWork: 'Meditations',
    bookChapter: 'Book 11',
    tags: ['anger', 'silence', 'restraint'],
    category: 'emotions',
  },
  {
    id: 'ma-030',
    text: 'If you are distressed by anything external, the pain is not due to the thing itself, but to your estimate of it; and this you have the power to revoke at any moment.',
    author: 'Marcus Aurelius',
    sourceWork: 'Meditations',
    bookChapter: 'Book 8',
    tags: ['perception', 'pain', 'control'],
    category: 'dichotomy_of_control',
  },
  {
    id: 'ma-031',
    text: 'How much time he gains who does not look to see what his neighbor says or does or thinks.',
    author: 'Marcus Aurelius',
    sourceWork: 'Meditations',
    bookChapter: 'Book 4',
    tags: ['focus', 'comparison', 'time'],
    category: 'self_improvement',
  },
  {
    id: 'ma-032',
    text: 'He who lives in harmony with himself lives in harmony with the universe.',
    author: 'Marcus Aurelius',
    sourceWork: 'Meditations',
    bookChapter: 'Book 5',
    tags: ['harmony', 'self', 'universe'],
    category: 'self_improvement',
  },
  {
    id: 'ma-033',
    text: 'Reject your sense of injury and the injury itself disappears.',
    author: 'Marcus Aurelius',
    sourceWork: 'Meditations',
    bookChapter: 'Book 4',
    tags: ['injury', 'perception', 'healing'],
    category: 'emotions',
  },
  {
    id: 'ma-034',
    text: 'When you wake up in the morning, tell yourself: The people I deal with today will be meddling, ungrateful, arrogant, dishonest, jealous, and surly.',
    author: 'Marcus Aurelius',
    sourceWork: 'Meditations',
    bookChapter: 'Book 2',
    tags: ['morning', 'preparation', 'people'],
    category: 'adversity',
  },
  {
    id: 'ma-035',
    text: 'The art of living is more like wrestling than dancing.',
    author: 'Marcus Aurelius',
    sourceWork: 'Meditations',
    bookChapter: 'Book 7',
    tags: ['life', 'struggle', 'resilience'],
    category: 'adversity',
  },
  {
    id: 'ma-036',
    text: 'Your days are numbered. Use them to throw open the windows of your soul to the sun.',
    author: 'Marcus Aurelius',
    sourceWork: 'Meditations',
    bookChapter: 'Book 2',
    tags: ['mortality', 'urgency', 'life'],
    category: 'mortality',
  },
  {
    id: 'ma-037',
    text: 'Do every act of your life as though it were the very last act of your life.',
    author: 'Marcus Aurelius',
    sourceWork: 'Meditations',
    bookChapter: 'Book 2',
    tags: ['action', 'mortality', 'intention'],
    category: 'mortality',
  },
  {
    id: 'ma-038',
    text: 'Our life is what our thoughts make it.',
    author: 'Marcus Aurelius',
    sourceWork: 'Meditations',
    bookChapter: 'Book 4',
    tags: ['thoughts', 'life', 'mindset'],
    category: 'self_improvement',
  },
  {
    id: 'ma-039',
    text: 'Whenever you are about to find fault with someone, ask yourself the following question: What fault of mine most nearly resembles the one I am about to criticize?',
    author: 'Marcus Aurelius',
    sourceWork: 'Meditations',
    bookChapter: 'Book 10',
    tags: ['criticism', 'self-reflection', 'humility'],
    category: 'relationships',
  },
  {
    id: 'ma-040',
    text: 'Adapt yourself to the things among which your lot has been cast and love sincerely the fellow creatures with whom destiny has ordained that you shall live.',
    author: 'Marcus Aurelius',
    sourceWork: 'Meditations',
    bookChapter: 'Book 6',
    tags: ['adaptation', 'love', 'acceptance'],
    category: 'relationships',
  },
  {
    id: 'ma-041',
    text: 'To live happily is an inward power of the soul.',
    author: 'Marcus Aurelius',
    sourceWork: 'Meditations',
    bookChapter: 'Book 11',
    tags: ['happiness', 'soul', 'inner-life'],
    category: 'self_improvement',
  },
  {
    id: 'ma-042',
    text: 'The universe is change; our life is what our thoughts make it.',
    author: 'Marcus Aurelius',
    sourceWork: 'Meditations',
    bookChapter: 'Book 4',
    tags: ['change', 'thoughts', 'universe'],
    category: 'present_moment',
  },
  {
    id: 'ma-043',
    text: 'Death smiles at us all; all a man can do is smile back.',
    author: 'Marcus Aurelius',
    sourceWork: 'Meditations',
    bookChapter: 'Book 7',
    tags: ['death', 'courage', 'acceptance'],
    category: 'mortality',
  },
  {
    id: 'ma-044',
    text: 'Let not your mind run on what you lack as much as on what you have already.',
    author: 'Marcus Aurelius',
    sourceWork: 'Meditations',
    bookChapter: 'Book 7',
    tags: ['gratitude', 'abundance', 'contentment'],
    category: 'present_moment',
  },
  {
    id: 'ma-045',
    text: 'Anger cannot be dishonest.',
    author: 'Marcus Aurelius',
    sourceWork: 'Meditations',
    bookChapter: 'Book 11',
    tags: ['anger', 'honesty', 'emotions'],
    category: 'emotions',
  },
  {
    id: 'ma-046',
    text: 'No one can lose either the past or the future - how could anyone be deprived of what he does not possess?',
    author: 'Marcus Aurelius',
    sourceWork: 'Meditations',
    bookChapter: 'Book 2',
    tags: ['time', 'present', 'loss'],
    category: 'present_moment',
  },
  {
    id: 'ma-047',
    text: 'Remember that man lives only in the present, in this fleeting instant; all the rest of his life is either past and gone, or not yet revealed.',
    author: 'Marcus Aurelius',
    sourceWork: 'Meditations',
    bookChapter: 'Book 3',
    tags: ['present', 'time', 'life'],
    category: 'present_moment',
  },
  {
    id: 'ma-048',
    text: 'Dig within. Within is the wellspring of Good; and it is always ready to bubble up, if you just dig.',
    author: 'Marcus Aurelius',
    sourceWork: 'Meditations',
    bookChapter: 'Book 7',
    tags: ['inner-life', 'goodness', 'self-discovery'],
    category: 'self_improvement',
  },
  {
    id: 'ma-049',
    text: 'A man should be upright, not be kept upright.',
    author: 'Marcus Aurelius',
    sourceWork: 'Meditations',
    bookChapter: 'Book 3',
    tags: ['integrity', 'character', 'independence'],
    category: 'virtue',
  },
  {
    id: 'ma-050',
    text: 'Here is a rule to remember in future, when anything tempts you to feel bitter: not "This is misfortune," but "To bear this worthily is good fortune."',
    author: 'Marcus Aurelius',
    sourceWork: 'Meditations',
    bookChapter: 'Book 4',
    tags: ['adversity', 'perspective', 'resilience'],
    category: 'adversity',
  },
  {
    id: 'ma-051',
    text: 'That which is not good for the swarm, is not good for the bee.',
    author: 'Marcus Aurelius',
    sourceWork: 'Meditations',
    bookChapter: 'Book 6',
    tags: ['community', 'society', 'ethics'],
    category: 'relationships',
  },
  {
    id: 'ma-052',
    text: 'Time is a sort of river of passing events, and strong is its current; no sooner is a thing brought to sight than it is swept by and another takes its place, and this too will be swept away.',
    author: 'Marcus Aurelius',
    sourceWork: 'Meditations',
    bookChapter: 'Book 4',
    tags: ['time', 'impermanence', 'change'],
    category: 'present_moment',
  },
  {
    id: 'ma-053',
    text: 'I have often wondered how it is that every man loves himself more than all the rest of men, but yet sets less value on his own opinion of himself than on the opinion of others.',
    author: 'Marcus Aurelius',
    sourceWork: 'Meditations',
    bookChapter: 'Book 12',
    tags: ['self-worth', 'opinion', 'others'],
    category: 'self_improvement',
  },
  {
    id: 'ma-054',
    text: 'Never value anything as profitable that compels you to break your promise, lose your self-respect, hate any man, suspect, curse, act the hypocrite, or desire anything that needs walls or curtains.',
    author: 'Marcus Aurelius',
    sourceWork: 'Meditations',
    bookChapter: 'Book 3',
    tags: ['values', 'integrity', 'character'],
    category: 'virtue',
  },
  {
    id: 'ma-055',
    text: 'The only wealth which you will keep forever is the wealth you have given away.',
    author: 'Marcus Aurelius',
    sourceWork: 'Meditations',
    bookChapter: 'Book 7',
    tags: ['generosity', 'wealth', 'giving'],
    category: 'virtue',
  },
  {
    id: 'ma-056',
    text: 'Mastery of reading and writing requires a master. Still more so life.',
    author: 'Marcus Aurelius',
    sourceWork: 'Meditations',
    bookChapter: 'Book 11',
    tags: ['learning', 'life', 'mastery'],
    category: 'self_improvement',
  },
  {
    id: 'ma-057',
    text: 'In the morning when thou risest unwillingly, let this thought be present: I am rising to the work of a human being.',
    author: 'Marcus Aurelius',
    sourceWork: 'Meditations',
    bookChapter: 'Book 5',
    tags: ['morning', 'purpose', 'work'],
    category: 'present_moment',
  },
  {
    id: 'ma-058',
    text: 'Nowhere can man find a quieter or more untroubled retreat than in his own soul.',
    author: 'Marcus Aurelius',
    sourceWork: 'Meditations',
    bookChapter: 'Book 4',
    tags: ['retreat', 'soul', 'peace'],
    category: 'self_improvement',
  },
  {
    id: 'ma-059',
    text: 'Execute every act of thy life as though it were thy last.',
    author: 'Marcus Aurelius',
    sourceWork: 'Meditations',
    bookChapter: 'Book 2',
    tags: ['action', 'mortality', 'intention'],
    category: 'mortality',
  },
  {
    id: 'ma-060',
    text: 'You are a little soul carrying about a corpse, as Epictetus used to say.',
    author: 'Marcus Aurelius',
    sourceWork: 'Meditations',
    bookChapter: 'Book 4',
    tags: ['soul', 'body', 'perspective'],
    category: 'mortality',
  },

  // EPICTETUS - Enchiridion & Discourses (60 quotes)
  {
    id: 'ep-001',
    text: 'Some things are in our control and others not. Things in our control are opinion, pursuit, desire, aversion, and, in a word, whatever are our own actions.',
    author: 'Epictetus',
    sourceWork: 'Enchiridion',
    bookChapter: 'Chapter 1',
    tags: ['control', 'action', 'choice'],
    category: 'dichotomy_of_control',
  },
  {
    id: 'ep-002',
    text: 'It\'s not what happens to you, but how you react to it that matters.',
    author: 'Epictetus',
    sourceWork: 'Enchiridion',
    bookChapter: 'Chapter 5',
    tags: ['reaction', 'events', 'choice'],
    category: 'dichotomy_of_control',
  },
  {
    id: 'ep-003',
    text: 'Man is not worried by real problems so much as by his imagined anxieties about real problems.',
    author: 'Epictetus',
    sourceWork: 'Enchiridion',
    bookChapter: 'Chapter 5',
    tags: ['anxiety', 'imagination', 'worry'],
    category: 'emotions',
  },
  {
    id: 'ep-004',
    text: 'Wealth consists not in having great possessions, but in having few wants.',
    author: 'Epictetus',
    sourceWork: 'Discourses',
    bookChapter: 'Book 4',
    tags: ['wealth', 'desires', 'contentment'],
    category: 'self_improvement',
  },
  {
    id: 'ep-005',
    text: 'First say to yourself what you would be; and then do what you have to do.',
    author: 'Epictetus',
    sourceWork: 'Discourses',
    bookChapter: 'Book 3',
    tags: ['identity', 'action', 'goals'],
    category: 'self_improvement',
  },
  {
    id: 'ep-006',
    text: 'No man is free who is not master of himself.',
    author: 'Epictetus',
    sourceWork: 'Discourses',
    bookChapter: 'Book 2',
    tags: ['freedom', 'self-mastery', 'discipline'],
    category: 'self_improvement',
  },
  {
    id: 'ep-007',
    text: 'Make the best use of what is in your power, and take the rest as it happens.',
    author: 'Epictetus',
    sourceWork: 'Discourses',
    bookChapter: 'Book 1',
    tags: ['control', 'acceptance', 'action'],
    category: 'dichotomy_of_control',
  },
  {
    id: 'ep-008',
    text: 'If you want to improve, be content to be thought foolish and stupid.',
    author: 'Epictetus',
    sourceWork: 'Enchiridion',
    bookChapter: 'Chapter 13',
    tags: ['growth', 'humility', 'judgment'],
    category: 'self_improvement',
  },
  {
    id: 'ep-009',
    text: 'Don\'t explain your philosophy. Embody it.',
    author: 'Epictetus',
    sourceWork: 'Enchiridion',
    bookChapter: 'Chapter 52',
    tags: ['action', 'philosophy', 'practice'],
    category: 'virtue',
  },
  {
    id: 'ep-010',
    text: 'There is only one way to happiness and that is to cease worrying about things which are beyond the power of our will.',
    author: 'Epictetus',
    sourceWork: 'Enchiridion',
    bookChapter: 'Chapter 1',
    tags: ['happiness', 'worry', 'control'],
    category: 'dichotomy_of_control',
  },
  {
    id: 'ep-011',
    text: 'He is a wise man who does not grieve for the things which he has not, but rejoices for those which he has.',
    author: 'Epictetus',
    sourceWork: 'Enchiridion',
    bookChapter: 'Chapter 17',
    tags: ['gratitude', 'wisdom', 'contentment'],
    category: 'present_moment',
  },
  {
    id: 'ep-012',
    text: 'Any person capable of angering you becomes your master.',
    author: 'Epictetus',
    sourceWork: 'Enchiridion',
    bookChapter: 'Chapter 28',
    tags: ['anger', 'control', 'power'],
    category: 'emotions',
  },
  {
    id: 'ep-013',
    text: 'Circumstances don\'t make the man, they only reveal him to himself.',
    author: 'Epictetus',
    sourceWork: 'Discourses',
    bookChapter: 'Book 1',
    tags: ['character', 'adversity', 'self-knowledge'],
    category: 'adversity',
  },
  {
    id: 'ep-014',
    text: 'We have two ears and one mouth so that we can listen twice as much as we speak.',
    author: 'Epictetus',
    sourceWork: 'Discourses',
    bookChapter: 'Book 2',
    tags: ['listening', 'wisdom', 'speech'],
    category: 'relationships',
  },
  {
    id: 'ep-015',
    text: 'It is impossible for a man to learn what he thinks he already knows.',
    author: 'Epictetus',
    sourceWork: 'Discourses',
    bookChapter: 'Book 2',
    tags: ['learning', 'humility', 'knowledge'],
    category: 'self_improvement',
  },
  {
    id: 'ep-016',
    text: 'Freedom is the only worthy goal in life. It is won by disregarding things that lie beyond our control.',
    author: 'Epictetus',
    sourceWork: 'Discourses',
    bookChapter: 'Book 1',
    tags: ['freedom', 'control', 'goals'],
    category: 'dichotomy_of_control',
  },
  {
    id: 'ep-017',
    text: 'The key is to keep company only with people who uplift you, whose presence calls forth your best.',
    author: 'Epictetus',
    sourceWork: 'Discourses',
    bookChapter: 'Book 3',
    tags: ['relationships', 'influence', 'growth'],
    category: 'relationships',
  },
  {
    id: 'ep-018',
    text: 'Seek not the good in external things; seek it in yourselves.',
    author: 'Epictetus',
    sourceWork: 'Discourses',
    bookChapter: 'Book 1',
    tags: ['inner-life', 'good', 'self'],
    category: 'self_improvement',
  },
  {
    id: 'ep-019',
    text: 'Caretake this moment. Immerse yourself in its particulars.',
    author: 'Epictetus',
    sourceWork: 'Discourses',
    bookChapter: 'Book 2',
    tags: ['present', 'mindfulness', 'attention'],
    category: 'present_moment',
  },
  {
    id: 'ep-020',
    text: 'You become what you give your attention to.',
    author: 'Epictetus',
    sourceWork: 'Discourses',
    bookChapter: 'Book 4',
    tags: ['attention', 'focus', 'identity'],
    category: 'self_improvement',
  },
  {
    id: 'ep-021',
    text: 'Attach yourself to what is spiritually superior, regardless of what other people think or do.',
    author: 'Epictetus',
    sourceWork: 'Enchiridion',
    bookChapter: 'Chapter 23',
    tags: ['values', 'spirituality', 'independence'],
    category: 'virtue',
  },
  {
    id: 'ep-022',
    text: 'People are not disturbed by things, but by the views they take of things.',
    author: 'Epictetus',
    sourceWork: 'Enchiridion',
    bookChapter: 'Chapter 5',
    tags: ['perception', 'judgment', 'disturbance'],
    category: 'dichotomy_of_control',
  },
  {
    id: 'ep-023',
    text: 'We are not privy to the stories behind people\'s actions, so we should be patient with others and suspend our judgment of them.',
    author: 'Epictetus',
    sourceWork: 'Enchiridion',
    bookChapter: 'Chapter 42',
    tags: ['judgment', 'patience', 'understanding'],
    category: 'relationships',
  },
  {
    id: 'ep-024',
    text: 'Be careful to leave your sons well instructed rather than rich, for the hopes of the instructed are better than the wealth of the ignorant.',
    author: 'Epictetus',
    sourceWork: 'Discourses',
    bookChapter: 'Book 3',
    tags: ['education', 'wealth', 'wisdom'],
    category: 'relationships',
  },
  {
    id: 'ep-025',
    text: 'Suffering arises from trying to control what is uncontrollable, or from neglecting what is within our power.',
    author: 'Epictetus',
    sourceWork: 'Discourses',
    bookChapter: 'Book 2',
    tags: ['suffering', 'control', 'power'],
    category: 'dichotomy_of_control',
  },
  {
    id: 'ep-026',
    text: 'To accuse others for one\'s own misfortunes is a sign of want of education. To accuse oneself shows that one\'s education has begun.',
    author: 'Epictetus',
    sourceWork: 'Enchiridion',
    bookChapter: 'Chapter 5',
    tags: ['responsibility', 'education', 'blame'],
    category: 'self_improvement',
  },
  {
    id: 'ep-027',
    text: 'If anyone tells you that a certain person speaks ill of you, do not make excuses about what is said of you but answer, "He was ignorant of my other faults, else he would not have mentioned these alone."',
    author: 'Epictetus',
    sourceWork: 'Enchiridion',
    bookChapter: 'Chapter 33',
    tags: ['criticism', 'humility', 'humor'],
    category: 'emotions',
  },
  {
    id: 'ep-028',
    text: 'Keep silence for the most part, and speak only when you must, and then briefly.',
    author: 'Epictetus',
    sourceWork: 'Enchiridion',
    bookChapter: 'Chapter 33',
    tags: ['silence', 'speech', 'restraint'],
    category: 'self_improvement',
  },
  {
    id: 'ep-029',
    text: 'Know, first, who you are, and then adorn yourself accordingly.',
    author: 'Epictetus',
    sourceWork: 'Discourses',
    bookChapter: 'Book 3',
    tags: ['identity', 'self-knowledge', 'authenticity'],
    category: 'self_improvement',
  },
  {
    id: 'ep-030',
    text: 'The essence of philosophy is that a man should so live that his happiness shall depend as little as possible on external things.',
    author: 'Epictetus',
    sourceWork: 'Discourses',
    bookChapter: 'Book 1',
    tags: ['philosophy', 'happiness', 'independence'],
    category: 'dichotomy_of_control',
  },
  {
    id: 'ep-031',
    text: 'Nature hath given men one tongue but two ears, that we may hear from others twice as much as we speak.',
    author: 'Epictetus',
    sourceWork: 'Discourses',
    bookChapter: 'Book 1',
    tags: ['listening', 'speaking', 'wisdom'],
    category: 'relationships',
  },
  {
    id: 'ep-032',
    text: 'Events do not just happen, but arrive by appointment.',
    author: 'Epictetus',
    sourceWork: 'Discourses',
    bookChapter: 'Book 2',
    tags: ['fate', 'events', 'acceptance'],
    category: 'adversity',
  },
  {
    id: 'ep-033',
    text: 'He who laughs at himself never runs out of things to laugh at.',
    author: 'Epictetus',
    sourceWork: 'Discourses',
    bookChapter: 'Book 1',
    tags: ['humor', 'self', 'perspective'],
    category: 'self_improvement',
  },
  {
    id: 'ep-034',
    text: 'Only the educated are free.',
    author: 'Epictetus',
    sourceWork: 'Discourses',
    bookChapter: 'Book 2',
    tags: ['education', 'freedom', 'knowledge'],
    category: 'self_improvement',
  },
  {
    id: 'ep-035',
    text: 'Small-minded people blame others. Average people blame themselves. The wise see all blame as foolishness.',
    author: 'Epictetus',
    sourceWork: 'Discourses',
    bookChapter: 'Book 1',
    tags: ['blame', 'wisdom', 'perspective'],
    category: 'self_improvement',
  },
  {
    id: 'ep-036',
    text: 'Practice yourself, for heaven\'s sake, in little things; and thence proceed to greater.',
    author: 'Epictetus',
    sourceWork: 'Discourses',
    bookChapter: 'Book 1',
    tags: ['practice', 'progress', 'discipline'],
    category: 'self_improvement',
  },
  {
    id: 'ep-037',
    text: 'What really frightens and dismays us is not external events themselves, but the way in which we think about them.',
    author: 'Epictetus',
    sourceWork: 'Enchiridion',
    bookChapter: 'Chapter 5',
    tags: ['fear', 'thinking', 'perception'],
    category: 'emotions',
  },
  {
    id: 'ep-038',
    text: 'If you wish to be a writer, write.',
    author: 'Epictetus',
    sourceWork: 'Discourses',
    bookChapter: 'Book 2',
    tags: ['action', 'practice', 'identity'],
    category: 'self_improvement',
  },
  {
    id: 'ep-039',
    text: 'Remember that you are an actor in a drama, of such a kind as the author pleases to make it.',
    author: 'Epictetus',
    sourceWork: 'Enchiridion',
    bookChapter: 'Chapter 17',
    tags: ['role', 'fate', 'acceptance'],
    category: 'dichotomy_of_control',
  },
  {
    id: 'ep-040',
    text: 'Tentative efforts lead to tentative outcomes. Therefore, give yourself fully to your endeavors.',
    author: 'Epictetus',
    sourceWork: 'Discourses',
    bookChapter: 'Book 2',
    tags: ['effort', 'commitment', 'action'],
    category: 'self_improvement',
  },
  {
    id: 'ep-041',
    text: 'Difficulty shows what men are.',
    author: 'Epictetus',
    sourceWork: 'Discourses',
    bookChapter: 'Book 1',
    tags: ['difficulty', 'character', 'adversity'],
    category: 'adversity',
  },
  {
    id: 'ep-042',
    text: 'Other people\'s views and troubles can be contagious. Don\'t sabotage yourself by unwittingly adopting negative, unproductive attitudes.',
    author: 'Epictetus',
    sourceWork: 'Enchiridion',
    bookChapter: 'Chapter 33',
    tags: ['attitudes', 'influence', 'mindset'],
    category: 'relationships',
  },
  {
    id: 'ep-043',
    text: 'Neither should a ship rely on one small anchor, nor should life rest on a single hope.',
    author: 'Epictetus',
    sourceWork: 'Discourses',
    bookChapter: 'Book 4',
    tags: ['hope', 'resilience', 'wisdom'],
    category: 'adversity',
  },
  {
    id: 'ep-044',
    text: 'If evil be spoken of you and it be true, correct yourself, if it be a lie, laugh at it.',
    author: 'Epictetus',
    sourceWork: 'Enchiridion',
    bookChapter: 'Chapter 33',
    tags: ['criticism', 'truth', 'humor'],
    category: 'emotions',
  },
  {
    id: 'ep-045',
    text: 'It is not so much what happens to you as how you think about what happens.',
    author: 'Epictetus',
    sourceWork: 'Enchiridion',
    bookChapter: 'Chapter 5',
    tags: ['perception', 'thinking', 'events'],
    category: 'dichotomy_of_control',
  },
  {
    id: 'ep-046',
    text: 'When you are offended at any man\'s fault, turn to yourself and study your own failings. Then you will forget your anger.',
    author: 'Epictetus',
    sourceWork: 'Enchiridion',
    bookChapter: 'Chapter 26',
    tags: ['anger', 'self-reflection', 'humility'],
    category: 'emotions',
  },
  {
    id: 'ep-047',
    text: 'Asked, who is the rich man? Epictetus replied, "He who is content."',
    author: 'Epictetus',
    sourceWork: 'Discourses',
    bookChapter: 'Book 3',
    tags: ['wealth', 'contentment', 'wisdom'],
    category: 'self_improvement',
  },
  {
    id: 'ep-048',
    text: 'Don\'t just say you have read books. Show that through them you have learned to think better.',
    author: 'Epictetus',
    sourceWork: 'Discourses',
    bookChapter: 'Book 2',
    tags: ['reading', 'thinking', 'wisdom'],
    category: 'self_improvement',
  },
  {
    id: 'ep-049',
    text: 'If someone criticizes you, agree at once. Mention that if only the critic knew you better, there would be more to criticize.',
    author: 'Epictetus',
    sourceWork: 'Enchiridion',
    bookChapter: 'Chapter 33',
    tags: ['criticism', 'humility', 'humor'],
    category: 'emotions',
  },
  {
    id: 'ep-050',
    text: 'On the occasion of every accident that befalls you, remember to turn to yourself and inquire what power you have for turning it to use.',
    author: 'Epictetus',
    sourceWork: 'Enchiridion',
    bookChapter: 'Chapter 10',
    tags: ['adversity', 'opportunity', 'power'],
    category: 'adversity',
  },
  {
    id: 'ep-051',
    text: 'We cannot choose our external circumstances, but we can always choose how we respond to them.',
    author: 'Epictetus',
    sourceWork: 'Discourses',
    bookChapter: 'Book 1',
    tags: ['choice', 'response', 'control'],
    category: 'dichotomy_of_control',
  },
  {
    id: 'ep-052',
    text: 'First learn the meaning of what you say, and then speak.',
    author: 'Epictetus',
    sourceWork: 'Discourses',
    bookChapter: 'Book 3',
    tags: ['speech', 'wisdom', 'understanding'],
    category: 'self_improvement',
  },
  {
    id: 'ep-053',
    text: 'Whoever is going to listen to the philosophers needs a considerable practice in listening.',
    author: 'Epictetus',
    sourceWork: 'Discourses',
    bookChapter: 'Book 2',
    tags: ['listening', 'philosophy', 'practice'],
    category: 'self_improvement',
  },
  {
    id: 'ep-054',
    text: 'A ship should not ride on a single anchor, nor life on a single hope.',
    author: 'Epictetus',
    sourceWork: 'Discourses',
    bookChapter: 'Book 4',
    tags: ['hope', 'wisdom', 'resilience'],
    category: 'adversity',
  },
  {
    id: 'ep-055',
    text: 'Crows pick out the eyes of the dead, when the dead have no longer need of them; but flatterers mar the soul of the living, and her eyes they blind.',
    author: 'Epictetus',
    sourceWork: 'Discourses',
    bookChapter: 'Book 4',
    tags: ['flattery', 'soul', 'truth'],
    category: 'relationships',
  },
  {
    id: 'ep-056',
    text: 'Nothing great is created suddenly, any more than a bunch of grapes or a fig.',
    author: 'Epictetus',
    sourceWork: 'Discourses',
    bookChapter: 'Book 1',
    tags: ['patience', 'growth', 'time'],
    category: 'self_improvement',
  },
  {
    id: 'ep-057',
    text: 'Control thy passions lest they take vengeance on thee.',
    author: 'Epictetus',
    sourceWork: 'Enchiridion',
    bookChapter: 'Chapter 34',
    tags: ['passions', 'control', 'emotions'],
    category: 'emotions',
  },
  {
    id: 'ep-058',
    text: 'Do not seek for things to happen the way you want them to; rather, wish that what happens happens the way it happens: then you will be happy.',
    author: 'Epictetus',
    sourceWork: 'Enchiridion',
    bookChapter: 'Chapter 8',
    tags: ['acceptance', 'happiness', 'fate'],
    category: 'dichotomy_of_control',
  },
  {
    id: 'ep-059',
    text: 'The greater the difficulty, the more glory in surmounting it. Skillful pilots gain their reputation from storms and tempests.',
    author: 'Epictetus',
    sourceWork: 'Discourses',
    bookChapter: 'Book 1',
    tags: ['difficulty', 'glory', 'adversity'],
    category: 'adversity',
  },
  {
    id: 'ep-060',
    text: 'You may fetter my leg, but Zeus himself cannot get the better of my free will.',
    author: 'Epictetus',
    sourceWork: 'Discourses',
    bookChapter: 'Book 1',
    tags: ['freedom', 'will', 'power'],
    category: 'dichotomy_of_control',
  },

  // SENECA - Letters & Essays (60 quotes)
  {
    id: 'se-001',
    text: 'Luck is what happens when preparation meets opportunity.',
    author: 'Seneca',
    sourceWork: 'Letters to Lucilius',
    bookChapter: 'Letter 73',
    tags: ['luck', 'preparation', 'opportunity'],
    category: 'self_improvement',
  },
  {
    id: 'se-002',
    text: 'We suffer more often in imagination than in reality.',
    author: 'Seneca',
    sourceWork: 'Letters to Lucilius',
    bookChapter: 'Letter 13',
    tags: ['suffering', 'imagination', 'anxiety'],
    category: 'emotions',
  },
  {
    id: 'se-003',
    text: 'It is not that we have a short time to live, but that we waste a lot of it.',
    author: 'Seneca',
    sourceWork: 'On the Shortness of Life',
    bookChapter: 'Chapter 1',
    tags: ['time', 'life', 'waste'],
    category: 'mortality',
  },
  {
    id: 'se-004',
    text: 'Begin at once to live, and count each separate day as a separate life.',
    author: 'Seneca',
    sourceWork: 'Letters to Lucilius',
    bookChapter: 'Letter 101',
    tags: ['life', 'present', 'beginning'],
    category: 'present_moment',
  },
  {
    id: 'se-005',
    text: 'As is a tale, so is life: not how long it is, but how good it is, is what matters.',
    author: 'Seneca',
    sourceWork: 'Letters to Lucilius',
    bookChapter: 'Letter 77',
    tags: ['life', 'quality', 'meaning'],
    category: 'mortality',
  },
  {
    id: 'se-006',
    text: 'If a man knows not to which port he sails, no wind is favorable.',
    author: 'Seneca',
    sourceWork: 'Letters to Lucilius',
    bookChapter: 'Letter 71',
    tags: ['purpose', 'direction', 'goals'],
    category: 'self_improvement',
  },
  {
    id: 'se-007',
    text: 'Difficulties strengthen the mind, as labor does the body.',
    author: 'Seneca',
    sourceWork: 'Letters to Lucilius',
    bookChapter: 'Letter 78',
    tags: ['difficulty', 'mind', 'strength'],
    category: 'adversity',
  },
  {
    id: 'se-008',
    text: 'True happiness is to enjoy the present, without anxious dependence upon the future.',
    author: 'Seneca',
    sourceWork: 'Letters to Lucilius',
    bookChapter: 'Letter 15',
    tags: ['happiness', 'present', 'future'],
    category: 'present_moment',
  },
  {
    id: 'se-009',
    text: 'The mind that is anxious about future events is miserable.',
    author: 'Seneca',
    sourceWork: 'Letters to Lucilius',
    bookChapter: 'Letter 98',
    tags: ['anxiety', 'future', 'misery'],
    category: 'emotions',
  },
  {
    id: 'se-010',
    text: 'Hang on to your youthful enthusiasms — you\'ll be able to use them better when you\'re older.',
    author: 'Seneca',
    sourceWork: 'Letters to Lucilius',
    bookChapter: 'Letter 36',
    tags: ['enthusiasm', 'youth', 'age'],
    category: 'self_improvement',
  },
  {
    id: 'se-011',
    text: 'No person has the power to have everything they want, but it is in their power not to want what they don\'t have.',
    author: 'Seneca',
    sourceWork: 'Letters to Lucilius',
    bookChapter: 'Letter 123',
    tags: ['desire', 'power', 'contentment'],
    category: 'self_improvement',
  },
  {
    id: 'se-012',
    text: 'While we wait for life, life passes.',
    author: 'Seneca',
    sourceWork: 'Letters to Lucilius',
    bookChapter: 'Letter 1',
    tags: ['life', 'waiting', 'time'],
    category: 'mortality',
  },
  {
    id: 'se-013',
    text: 'We are more often frightened than hurt; and we suffer more from imagination than from reality.',
    author: 'Seneca',
    sourceWork: 'Letters to Lucilius',
    bookChapter: 'Letter 13',
    tags: ['fear', 'imagination', 'reality'],
    category: 'emotions',
  },
  {
    id: 'se-014',
    text: 'He who is brave is free.',
    author: 'Seneca',
    sourceWork: 'Letters to Lucilius',
    bookChapter: 'Letter 85',
    tags: ['bravery', 'freedom', 'courage'],
    category: 'virtue',
  },
  {
    id: 'se-015',
    text: 'Enjoy present pleasures in such a way as not to injure future ones.',
    author: 'Seneca',
    sourceWork: 'Letters to Lucilius',
    bookChapter: 'Letter 15',
    tags: ['pleasure', 'present', 'future'],
    category: 'present_moment',
  },
  {
    id: 'se-016',
    text: 'Most powerful is he who has himself in his own power.',
    author: 'Seneca',
    sourceWork: 'Letters to Lucilius',
    bookChapter: 'Letter 90',
    tags: ['power', 'self-control', 'mastery'],
    category: 'self_improvement',
  },
  {
    id: 'se-017',
    text: 'Life is very short and anxious for those who forget the past, neglect the present, and fear the future.',
    author: 'Seneca',
    sourceWork: 'On the Shortness of Life',
    bookChapter: 'Chapter 10',
    tags: ['life', 'time', 'anxiety'],
    category: 'present_moment',
  },
  {
    id: 'se-018',
    text: 'Associate with people who are likely to improve you.',
    author: 'Seneca',
    sourceWork: 'Letters to Lucilius',
    bookChapter: 'Letter 7',
    tags: ['relationships', 'improvement', 'influence'],
    category: 'relationships',
  },
  {
    id: 'se-019',
    text: 'Every night before going to sleep, we must ask ourselves: What weakness did I overcome today? What virtue did I acquire?',
    author: 'Seneca',
    sourceWork: 'On Anger',
    bookChapter: 'Book 3',
    tags: ['reflection', 'evening', 'growth'],
    category: 'self_improvement',
  },
  {
    id: 'se-020',
    text: 'Sometimes even to live is an act of courage.',
    author: 'Seneca',
    sourceWork: 'Letters to Lucilius',
    bookChapter: 'Letter 78',
    tags: ['courage', 'life', 'adversity'],
    category: 'adversity',
  },
  {
    id: 'se-021',
    text: 'The whole future lies in uncertainty: live immediately.',
    author: 'Seneca',
    sourceWork: 'Letters to Lucilius',
    bookChapter: 'Letter 101',
    tags: ['future', 'uncertainty', 'present'],
    category: 'present_moment',
  },
  {
    id: 'se-022',
    text: 'It is not because things are difficult that we do not dare; it is because we do not dare that things are difficult.',
    author: 'Seneca',
    sourceWork: 'Letters to Lucilius',
    bookChapter: 'Letter 104',
    tags: ['difficulty', 'courage', 'action'],
    category: 'adversity',
  },
  {
    id: 'se-023',
    text: 'Wealth is the slave of a wise man and the master of a fool.',
    author: 'Seneca',
    sourceWork: 'Letters to Lucilius',
    bookChapter: 'Letter 119',
    tags: ['wealth', 'wisdom', 'mastery'],
    category: 'self_improvement',
  },
  {
    id: 'se-024',
    text: 'You act like mortals in all that you fear, and like immortals in all that you desire.',
    author: 'Seneca',
    sourceWork: 'On the Shortness of Life',
    bookChapter: 'Chapter 3',
    tags: ['mortality', 'desire', 'fear'],
    category: 'mortality',
  },
  {
    id: 'se-025',
    text: 'Expecting is the greatest impediment to living. In anticipation of tomorrow, it loses today.',
    author: 'Seneca',
    sourceWork: 'Letters to Lucilius',
    bookChapter: 'Letter 45',
    tags: ['expectation', 'present', 'living'],
    category: 'present_moment',
  },
  {
    id: 'se-026',
    text: 'A gem cannot be polished without friction, nor a man perfected without trials.',
    author: 'Seneca',
    sourceWork: 'Letters to Lucilius',
    bookChapter: 'Letter 67',
    tags: ['trials', 'perfection', 'adversity'],
    category: 'adversity',
  },
  {
    id: 'se-027',
    text: 'What need is there to weep over parts of life? The whole of it calls for tears.',
    author: 'Seneca',
    sourceWork: 'Letters to Lucilius',
    bookChapter: 'Letter 99',
    tags: ['life', 'perspective', 'sorrow'],
    category: 'mortality',
  },
  {
    id: 'se-028',
    text: 'The greatest blessings of mankind are within us and within our reach. A wise man is content with his lot, whatever it may be, without wishing for what he has not.',
    author: 'Seneca',
    sourceWork: 'Letters to Lucilius',
    bookChapter: 'Letter 9',
    tags: ['blessings', 'contentment', 'wisdom'],
    category: 'self_improvement',
  },
  {
    id: 'se-029',
    text: 'The sun also shines on the wicked.',
    author: 'Seneca',
    sourceWork: 'On Benefits',
    bookChapter: 'Book 4',
    tags: ['equality', 'nature', 'perspective'],
    category: 'virtue',
  },
  {
    id: 'se-030',
    text: 'Throw me to the wolves and I will return leading the pack.',
    author: 'Seneca',
    sourceWork: 'Letters to Lucilius',
    bookChapter: 'Letter 37',
    tags: ['adversity', 'strength', 'leadership'],
    category: 'adversity',
  },
  {
    id: 'se-031',
    text: 'One of the most beautiful qualities of true friendship is to understand and to be understood.',
    author: 'Seneca',
    sourceWork: 'Letters to Lucilius',
    bookChapter: 'Letter 3',
    tags: ['friendship', 'understanding', 'connection'],
    category: 'relationships',
  },
  {
    id: 'se-032',
    text: 'All cruelty springs from weakness.',
    author: 'Seneca',
    sourceWork: 'Letters to Lucilius',
    bookChapter: 'Letter 81',
    tags: ['cruelty', 'weakness', 'character'],
    category: 'emotions',
  },
  {
    id: 'se-033',
    text: 'Anger, if not restrained, is frequently more hurtful to us than the injury that provokes it.',
    author: 'Seneca',
    sourceWork: 'On Anger',
    bookChapter: 'Book 1',
    tags: ['anger', 'restraint', 'harm'],
    category: 'emotions',
  },
  {
    id: 'se-034',
    text: 'The time will come when diligent research over long periods will bring to light things which now lie hidden.',
    author: 'Seneca',
    sourceWork: 'Natural Questions',
    bookChapter: 'Book 7',
    tags: ['research', 'discovery', 'time'],
    category: 'self_improvement',
  },
  {
    id: 'se-035',
    text: 'No man is good by chance. Virtue is something that must be learned.',
    author: 'Seneca',
    sourceWork: 'Letters to Lucilius',
    bookChapter: 'Letter 123',
    tags: ['virtue', 'learning', 'effort'],
    category: 'virtue',
  },
  {
    id: 'se-036',
    text: 'Whatever can happen at any time can happen today.',
    author: 'Seneca',
    sourceWork: 'Letters to Lucilius',
    bookChapter: 'Letter 63',
    tags: ['time', 'present', 'preparation'],
    category: 'present_moment',
  },
  {
    id: 'se-037',
    text: 'Nothing is more honorable than a grateful heart.',
    author: 'Seneca',
    sourceWork: 'On Benefits',
    bookChapter: 'Book 2',
    tags: ['gratitude', 'honor', 'heart'],
    category: 'virtue',
  },
  {
    id: 'se-038',
    text: 'Whenever you want to cheer yourself up, consider the good qualities of your companions.',
    author: 'Seneca',
    sourceWork: 'Letters to Lucilius',
    bookChapter: 'Letter 59',
    tags: ['cheerfulness', 'friends', 'appreciation'],
    category: 'relationships',
  },
  {
    id: 'se-039',
    text: 'The greatest remedy for anger is delay.',
    author: 'Seneca',
    sourceWork: 'On Anger',
    bookChapter: 'Book 2',
    tags: ['anger', 'delay', 'remedy'],
    category: 'emotions',
  },
  {
    id: 'se-040',
    text: 'Life, if well lived, is long enough.',
    author: 'Seneca',
    sourceWork: 'On the Shortness of Life',
    bookChapter: 'Chapter 1',
    tags: ['life', 'living', 'enough'],
    category: 'mortality',
  },
  {
    id: 'se-041',
    text: 'He suffers more than necessary, who suffers before it is necessary.',
    author: 'Seneca',
    sourceWork: 'Letters to Lucilius',
    bookChapter: 'Letter 98',
    tags: ['suffering', 'anticipation', 'unnecessary'],
    category: 'emotions',
  },
  {
    id: 'se-042',
    text: 'There is no genius without a touch of madness.',
    author: 'Seneca',
    sourceWork: 'On Tranquility of Mind',
    bookChapter: 'Chapter 17',
    tags: ['genius', 'madness', 'creativity'],
    category: 'self_improvement',
  },
  {
    id: 'se-043',
    text: 'Be not too hasty to trust or admire the teachers of morality: they discourse like angels but they live like men.',
    author: 'Seneca',
    sourceWork: 'Letters to Lucilius',
    bookChapter: 'Letter 52',
    tags: ['teachers', 'morality', 'judgment'],
    category: 'relationships',
  },
  {
    id: 'se-044',
    text: 'What progress have I made? I am beginning to be my own friend.',
    author: 'Seneca',
    sourceWork: 'Letters to Lucilius',
    bookChapter: 'Letter 6',
    tags: ['progress', 'friendship', 'self'],
    category: 'self_improvement',
  },
  {
    id: 'se-045',
    text: 'Not how long, but how well you have lived is the main thing.',
    author: 'Seneca',
    sourceWork: 'Letters to Lucilius',
    bookChapter: 'Letter 77',
    tags: ['life', 'quality', 'living'],
    category: 'mortality',
  },
  {
    id: 'se-046',
    text: 'No wind favors him who has no destined port.',
    author: 'Seneca',
    sourceWork: 'Letters to Lucilius',
    bookChapter: 'Letter 71',
    tags: ['purpose', 'direction', 'goals'],
    category: 'self_improvement',
  },
  {
    id: 'se-047',
    text: 'We learn not in the school, but in life.',
    author: 'Seneca',
    sourceWork: 'Letters to Lucilius',
    bookChapter: 'Letter 106',
    tags: ['learning', 'life', 'experience'],
    category: 'self_improvement',
  },
  {
    id: 'se-048',
    text: 'A man who suffers before it is necessary, suffers more than is necessary.',
    author: 'Seneca',
    sourceWork: 'Letters to Lucilius',
    bookChapter: 'Letter 74',
    tags: ['suffering', 'anticipation', 'worry'],
    category: 'emotions',
  },
  {
    id: 'se-049',
    text: 'Retire into yourself as much as possible. Associate with people who are likely to improve you.',
    author: 'Seneca',
    sourceWork: 'Letters to Lucilius',
    bookChapter: 'Letter 7',
    tags: ['solitude', 'association', 'improvement'],
    category: 'self_improvement',
  },
  {
    id: 'se-050',
    text: 'Religion is regarded by the common people as true, by the wise as false, and by rulers as useful.',
    author: 'Seneca',
    sourceWork: 'Letters to Lucilius',
    bookChapter: 'Letter 95',
    tags: ['religion', 'wisdom', 'society'],
    category: 'virtue',
  },
  {
    id: 'se-051',
    text: 'The bravest sight in the world is to see a great man struggling against adversity.',
    author: 'Seneca',
    sourceWork: 'On Providence',
    bookChapter: 'Chapter 2',
    tags: ['bravery', 'adversity', 'greatness'],
    category: 'adversity',
  },
  {
    id: 'se-052',
    text: 'It is quality rather than quantity that matters.',
    author: 'Seneca',
    sourceWork: 'Letters to Lucilius',
    bookChapter: 'Letter 45',
    tags: ['quality', 'quantity', 'value'],
    category: 'self_improvement',
  },
  {
    id: 'se-053',
    text: 'Fire tests gold, suffering tests brave men.',
    author: 'Seneca',
    sourceWork: 'On Providence',
    bookChapter: 'Chapter 5',
    tags: ['suffering', 'testing', 'bravery'],
    category: 'adversity',
  },
  {
    id: 'se-054',
    text: 'Fate leads the willing and drags along the reluctant.',
    author: 'Seneca',
    sourceWork: 'Letters to Lucilius',
    bookChapter: 'Letter 107',
    tags: ['fate', 'acceptance', 'resistance'],
    category: 'dichotomy_of_control',
  },
  {
    id: 'se-055',
    text: 'You want to live—but do you know how to live? You are scared of dying—and, tell me, is the kind of life you lead really any different from being dead?',
    author: 'Seneca',
    sourceWork: 'Letters to Lucilius',
    bookChapter: 'Letter 77',
    tags: ['life', 'death', 'living'],
    category: 'mortality',
  },
  {
    id: 'se-056',
    text: 'Let us prepare our minds as if we\'d come to the very end of life.',
    author: 'Seneca',
    sourceWork: 'Letters to Lucilius',
    bookChapter: 'Letter 61',
    tags: ['preparation', 'death', 'mind'],
    category: 'mortality',
  },
  {
    id: 'se-057',
    text: 'Leisure without books is death, and burial of a man alive.',
    author: 'Seneca',
    sourceWork: 'Letters to Lucilius',
    bookChapter: 'Letter 82',
    tags: ['leisure', 'books', 'reading'],
    category: 'self_improvement',
  },
  {
    id: 'se-058',
    text: 'There are more things likely to frighten us than there are to crush us; we suffer more in imagination than in reality.',
    author: 'Seneca',
    sourceWork: 'Letters to Lucilius',
    bookChapter: 'Letter 13',
    tags: ['fear', 'imagination', 'reality'],
    category: 'emotions',
  },
  {
    id: 'se-059',
    text: 'I shall never be ashamed of citing a bad author if the line is good.',
    author: 'Seneca',
    sourceWork: 'On Tranquility of Mind',
    bookChapter: 'Chapter 11',
    tags: ['wisdom', 'source', 'truth'],
    category: 'self_improvement',
  },
  {
    id: 'se-060',
    text: 'If you live in harmony with nature you will never be poor; if you live according what others think, you will never be rich.',
    author: 'Seneca',
    sourceWork: 'Letters to Lucilius',
    bookChapter: 'Letter 16',
    tags: ['nature', 'wealth', 'opinion'],
    category: 'self_improvement',
  },

  // OTHER STOICS (20 quotes)
  {
    id: 'mr-001',
    text: 'If you accomplish something good with hard work, the labor passes quickly, but the good endures.',
    author: 'Musonius Rufus',
    sourceWork: 'Lectures',
    bookChapter: 'Lecture 7',
    tags: ['work', 'endurance', 'good'],
    category: 'self_improvement',
  },
  {
    id: 'mr-002',
    text: 'We begin to lose our hesitation to do immoral things when we lose our hesitation to speak of them.',
    author: 'Musonius Rufus',
    sourceWork: 'Lectures',
    bookChapter: 'Lecture 8',
    tags: ['speech', 'morality', 'action'],
    category: 'virtue',
  },
  {
    id: 'mr-003',
    text: 'How much better to be known for doing well by many than for living extravagantly?',
    author: 'Musonius Rufus',
    sourceWork: 'Lectures',
    bookChapter: 'Lecture 19',
    tags: ['reputation', 'doing good', 'simplicity'],
    category: 'virtue',
  },
  {
    id: 'mr-004',
    text: 'In order to protect ourselves we must live like doctors and be continually treating ourselves with reason.',
    author: 'Musonius Rufus',
    sourceWork: 'Lectures',
    bookChapter: 'Lecture 5',
    tags: ['reason', 'self-care', 'wisdom'],
    category: 'self_improvement',
  },
  {
    id: 'mr-005',
    text: 'Since every man dies, it is better to die with distinction than to live long.',
    author: 'Musonius Rufus',
    sourceWork: 'Lectures',
    bookChapter: 'Lecture 6',
    tags: ['death', 'distinction', 'honor'],
    category: 'mortality',
  },
  {
    id: 'cl-001',
    text: 'To be even-minded is the greatest virtue.',
    author: 'Cleanthes',
    sourceWork: 'Fragments',
    bookChapter: 'Fragment 1',
    tags: ['virtue', 'equanimity', 'mind'],
    category: 'virtue',
  },
  {
    id: 'cl-002',
    text: 'Lead me, Zeus, and you too, Destiny, wherever your decrees have assigned me.',
    author: 'Cleanthes',
    sourceWork: 'Hymn to Zeus',
    bookChapter: null,
    tags: ['fate', 'acceptance', 'destiny'],
    category: 'dichotomy_of_control',
  },
  {
    id: 'cl-003',
    text: 'The willing are led by fate, the reluctant are dragged.',
    author: 'Cleanthes',
    sourceWork: 'Fragments',
    bookChapter: null,
    tags: ['fate', 'acceptance', 'will'],
    category: 'dichotomy_of_control',
  },
  {
    id: 'zn-001',
    text: 'Man conquers the world by conquering himself.',
    author: 'Zeno of Citium',
    sourceWork: 'Fragments',
    bookChapter: null,
    tags: ['conquest', 'self-mastery', 'world'],
    category: 'self_improvement',
  },
  {
    id: 'zn-002',
    text: 'We have two ears and one mouth, so we should listen more than we speak.',
    author: 'Zeno of Citium',
    sourceWork: 'Fragments',
    bookChapter: null,
    tags: ['listening', 'speaking', 'wisdom'],
    category: 'relationships',
  },
  {
    id: 'zn-003',
    text: 'The goal of life is living in agreement with nature.',
    author: 'Zeno of Citium',
    sourceWork: 'Fragments',
    bookChapter: null,
    tags: ['life', 'nature', 'agreement'],
    category: 'virtue',
  },
  {
    id: 'zn-004',
    text: 'Well-being is realized by small steps, but is truly no small thing.',
    author: 'Zeno of Citium',
    sourceWork: 'Fragments',
    bookChapter: null,
    tags: ['well-being', 'progress', 'steps'],
    category: 'self_improvement',
  },
  {
    id: 'zn-005',
    text: 'Nothing is more hostile to a firm grasp on knowledge than self-deception.',
    author: 'Zeno of Citium',
    sourceWork: 'Fragments',
    bookChapter: null,
    tags: ['knowledge', 'self-deception', 'truth'],
    category: 'self_improvement',
  },
  {
    id: 'ch-001',
    text: 'He who has courage and faith will never perish in misery.',
    author: 'Chrysippus',
    sourceWork: 'Fragments',
    bookChapter: null,
    tags: ['courage', 'faith', 'misery'],
    category: 'adversity',
  },
  {
    id: 'ch-002',
    text: 'The universe itself is god and the universal outpouring of its soul.',
    author: 'Chrysippus',
    sourceWork: 'On Nature',
    bookChapter: null,
    tags: ['universe', 'god', 'nature'],
    category: 'virtue',
  },
  {
    id: 'ct-001',
    text: 'I begin to speak only when I\'m certain what I\'ll say isn\'t better left unsaid.',
    author: 'Cato the Elder',
    sourceWork: 'Sayings',
    bookChapter: null,
    tags: ['speech', 'silence', 'wisdom'],
    category: 'self_improvement',
  },
  {
    id: 'ct-002',
    text: 'Wise men learn more from fools than fools from the wise.',
    author: 'Cato the Elder',
    sourceWork: 'Sayings',
    bookChapter: null,
    tags: ['wisdom', 'learning', 'fools'],
    category: 'self_improvement',
  },
  {
    id: 'ct-003',
    text: 'An angry man opens his mouth and shuts his eyes.',
    author: 'Cato the Elder',
    sourceWork: 'Sayings',
    bookChapter: null,
    tags: ['anger', 'blindness', 'speech'],
    category: 'emotions',
  },
  {
    id: 'hy-001',
    text: 'Seek not good from without: seek it within yourselves, or you will never find it.',
    author: 'Hierocles',
    sourceWork: 'Fragments',
    bookChapter: null,
    tags: ['good', 'within', 'seeking'],
    category: 'self_improvement',
  },
  {
    id: 'po-001',
    text: 'Some things are rushing into existence, others out of it. Some of what now exists is already gone.',
    author: 'Posidonius',
    sourceWork: 'Fragments',
    bookChapter: null,
    tags: ['change', 'impermanence', 'existence'],
    category: 'present_moment',
  },
];
